package com.vehiclediag.app.data.models

import com.google.gson.annotations.SerializedName

// ═══════════════════════════════════════════════════════════════════════════
// Vehicle Telemetry Models
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Complete vehicle telemetry data from backend.
 */
data class VehicleTelemetry(
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("speed") val speed: Double = 0.0,
    @SerializedName("battery") val battery: BatteryHealth = BatteryHealth(),
    @SerializedName("tires") val tires: TireStatus = TireStatus(),
    @SerializedName("drivetrain") val drivetrain: DrivetrainStatus = DrivetrainStatus(),
    @SerializedName("ev_status") val evStatus: EVStatus = EVStatus(),
    @SerializedName("gps") val gps: GPSLocation = GPSLocation(),
    @SerializedName("odometer") val odometer: Double = 0.0,
    @SerializedName("engine_status") val engineStatus: String = "unknown",
    @SerializedName("vehicle_variant") val vehicleVariant: String = "EV"
)

/**
 * Battery state of charge and health.
 */
data class BatteryHealth(
    @SerializedName("soc") val soc: Double = 0.0,
    @SerializedName("voltage") val voltage: Double = 0.0,
    @SerializedName("temperature") val temperature: Double = 0.0,
    @SerializedName("health_status") val healthStatus: String = "Unknown"
)

/**
 * Tire pressure for all four tires.
 */
data class TireStatus(
    @SerializedName("front_left") val frontLeft: Double = 0.0,
    @SerializedName("front_right") val frontRight: Double = 0.0,
    @SerializedName("rear_left") val rearLeft: Double = 0.0,
    @SerializedName("rear_right") val rearRight: Double = 0.0
)

/**
 * Drivetrain status — throttle, brake, gear, steering.
 */
data class DrivetrainStatus(
    @SerializedName("throttle_position") val throttlePosition: Double = 0.0,
    @SerializedName("brake_position") val brakePosition: Double = 0.0,
    @SerializedName("gear_position") val gearPosition: String = "P",
    @SerializedName("steering_angle") val steeringAngle: Double = 0.0
)

/**
 * EV-specific status — range, charging, regen braking.
 */
data class EVStatus(
    @SerializedName("ev_range") val evRange: Double = 0.0,
    @SerializedName("charging") val charging: Boolean = false,
    @SerializedName("regen_braking") val regenBraking: Boolean = false
)

/**
 * GPS coordinates.
 */
data class GPSLocation(
    @SerializedName("latitude") val latitude: Double = 0.0,
    @SerializedName("longitude") val longitude: Double = 0.0
)

// ═══════════════════════════════════════════════════════════════════════════
// Alert Model
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Alert generated by the health analytics engine.
 */
data class AlertModel(
    @SerializedName("id") val id: String = "",
    @SerializedName("alert_type") val alertType: String = "",
    @SerializedName("severity") val severity: String = "info",
    @SerializedName("message") val message: String = "",
    @SerializedName("signal") val signal: String = "",
    @SerializedName("value") val value: Double = 0.0,
    @SerializedName("threshold") val threshold: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("acknowledged") val acknowledged: Boolean = false
)

// ═══════════════════════════════════════════════════════════════════════════
// Simulation Models
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Simulation status from backend.
 */
data class SimulationStatus(
    @SerializedName("running") val running: Boolean = false,
    @SerializedName("tick_count") val tickCount: Int = 0,
    @SerializedName("start_time") val startTime: String? = null,
    @SerializedName("message") val message: String = ""
)

/**
 * Speed response from /vehicle/speed endpoint.
 */
data class SpeedResponse(
    @SerializedName("speed") val speed: Double = 0.0,
    @SerializedName("unit") val unit: String = "km/h",
    @SerializedName("timestamp") val timestamp: String = ""
)

// ═══════════════════════════════════════════════════════════════════════════
// Configuration Models
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Dynamic signal configuration for OTA.
 */
data class SignalConfigResponse(
    @SerializedName("signals") val signals: List<SignalConfig> = emptyList(),
    @SerializedName("count") val count: Int = 0
)

data class SignalConfig(
    @SerializedName("id") val id: String = "",
    @SerializedName("name") val name: String = "",
    @SerializedName("unit") val unit: String = "",
    @SerializedName("min") val min: Double = 0.0,
    @SerializedName("max") val max: Double = 0.0,
    @SerializedName("normal_range") val normalRange: List<Double> = emptyList(),
    @SerializedName("ui_widget") val uiWidget: String = ""
)

// ═══════════════════════════════════════════════════════════════════════════
// Code Generation Models
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Request body for the /codegen/generate endpoint.
 */
data class CodeGenRequest(
    @SerializedName("requirement") val requirement: String,
    @SerializedName("language") val language: String = "python"
)

/**
 * Generated code details from the backend.
 */
data class GeneratedCode(
    @SerializedName("language") val language: String = "",
    @SerializedName("language_name") val languageName: String = "",
    @SerializedName("code") val code: String = "",
    @SerializedName("lines_of_code") val linesOfCode: Int = 0,
    @SerializedName("generation_method") val generationMethod: String = "",
    @SerializedName("generation_time_ms") val generationTimeMs: Int = 0
)

/**
 * Response from /codegen/generate endpoint.
 */
data class CodeGenResponse(
    @SerializedName("requirement") val requirement: String = "",
    @SerializedName("signals_detected") val signalsDetected: List<String> = emptyList(),
    @SerializedName("generated_code") val generatedCode: GeneratedCode = GeneratedCode()
)

/**
 * Response from /codegen/languages endpoint.
 */
data class LanguagesResponse(
    @SerializedName("languages") val languages: List<String> = emptyList()
)
